# Generated by Django 3.2.12 on 2024-05-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0009_alter_message_eml'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='imap_uid',
            field=models.CharField(default=0, max_length=255, verbose_name='Message ID'),
            preserve_default=False,
        ),
    ]
