# Generated by Django 3.2.12 on 2024-05-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0010_message_imap_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='imap_uid',
            field=models.CharField(max_length=255, verbose_name='IMAP UID'),
        ),
    ]
